# Generated by Django 2.2 on 2019-04-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100)),
                ('book_user_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('book_comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100)),
                ('book_provider_mail', models.EmailField(max_length=254)),
                ('book_isbn10', models.CharField(max_length=10)),
                ('book_author', models.CharField(max_length=20)),
                ('book_publisher', models.CharField(max_length=20)),
                ('book_copies', models.IntegerField()),
                ('book_price', models.IntegerField()),
                ('book_description', models.TextField()),
                ('book_language', models.CharField(max_length=20)),
                ('book_year', models.CharField(max_length=4)),
                ('book_image', models.ImageField(blank=True, upload_to='')),
                ('book_category', models.TextField(max_length=50)),
                ('book_rating', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('book_title', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('items', models.IntegerField(default=1)),
                ('cost', models.IntegerField(default=0)),
                ('status', models.CharField(default='no', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mail', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('rating_value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('user_mail', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=20)),
                ('user_number', models.CharField(max_length=10)),
                ('user_address', models.TextField()),
                ('user_role', models.CharField(default='costumer', max_length=10)),
            ],
        ),
    ]
