# Generated by Django 2.2 on 2019-04-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190423_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'User'},
        ),
    ]
