# Generated by Django 2.2 on 2019-04-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20190423_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_mail', models.EmailField(max_length=254)),
                ('card_name', models.CharField(max_length=10)),
                ('card_number', models.CharField(max_length=10)),
                ('card_cvv', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Card_details',
            },
        ),
    ]
