# Generated by Django 2.2 on 2019-04-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_card_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_details',
            name='card_cvv',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='card_details',
            name='card_name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='card_details',
            name='card_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
