# Generated by Django 2.2 on 2019-04-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20190426_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_status',
            field=models.CharField(default='on', max_length=20),
        ),
    ]
