# Generated by Django 2.2 on 2019-04-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_categories_category_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_title', models.CharField(max_length=100)),
                ('order_provider_mail', models.EmailField(max_length=254)),
                ('order_isbn10', models.CharField(max_length=10)),
                ('order_author', models.CharField(max_length=20)),
                ('order_publisher', models.CharField(max_length=20)),
                ('order_copies', models.IntegerField()),
                ('order_price', models.IntegerField()),
                ('order_description', models.TextField()),
                ('order_language', models.CharField(max_length=20)),
                ('order_year', models.CharField(max_length=4)),
                ('order_image', models.ImageField(blank=True, upload_to='')),
                ('order_category', models.TextField(max_length=50)),
                ('order_rating', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
