# Generated by Django 2.2 on 2019-04-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_mail',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
