# Generated by Django 2.2 on 2019-04-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_orders_order_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_status',
            field=models.CharField(default='on', max_length=3),
        ),
    ]
